/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */

export type ActivityItemType =
  (typeof ActivityItemType)[keyof typeof ActivityItemType];

export const ActivityItemType = {
  question: "question",
  answer: "answer",
  ai_answer: "ai_answer",
} as const;
