/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */

export interface Answer {
  id: number;
  body: string;
  questionId: number;
  /** @nullable */
  authorId?: number | null;
  authorUsername: string;
  authorDisplayName: string;
  /** @nullable */
  authorAvatarUrl?: string | null;
  isAiGenerated: boolean;
  isVerified: boolean;
  /** @nullable */
  verificationNote?: string | null;
  isAccepted: boolean;
  voteCount: number;
  createdAt: Date;
}
