/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Create or get user
 */
export const CreateUserBody = zod.object({
  username: zod.string(),
  displayName: zod.string(),
  avatarUrl: zod.string().optional(),
});

export const CreateUserResponse = zod.object({
  id: zod.number(),
  clerkUserId: zod.string().nullish(),
  username: zod.string(),
  email: zod.string().nullish(),
  displayName: zod.string(),
  avatarUrl: zod.string().nullish(),
  reputation: zod.number(),
  questionsCount: zod.number(),
  answersCount: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Create or update the signed-in user's community profile
 */
export const UpsertCurrentUserBody = zod.object({
  username: zod.string(),
  displayName: zod.string(),
  email: zod.string().nullish(),
  avatarUrl: zod.string().nullish(),
});

export const UpsertCurrentUserResponse = zod.object({
  id: zod.number(),
  clerkUserId: zod.string().nullish(),
  username: zod.string(),
  email: zod.string().nullish(),
  displayName: zod.string(),
  avatarUrl: zod.string().nullish(),
  reputation: zod.number(),
  questionsCount: zod.number(),
  answersCount: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary List questions with filters
 */
export const listQuestionsQuerySortDefault = `recent`;
export const listQuestionsQueryPageDefault = 1;
export const listQuestionsQueryLimitDefault = 20;

export const ListQuestionsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  status: zod.enum(["open", "answered", "ai_answered"]).optional(),
  sort: zod
    .enum(["recent", "popular", "unanswered"])
    .default(listQuestionsQuerySortDefault),
  search: zod.coerce.string().optional(),
  page: zod.coerce.number().default(listQuestionsQueryPageDefault),
  limit: zod.coerce.number().default(listQuestionsQueryLimitDefault),
});

export const ListQuestionsResponse = zod.object({
  questions: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      body: zod.string(),
      category: zod.string(),
      tags: zod.array(zod.string()),
      status: zod.enum(["open", "answered", "ai_answered"]),
      voteCount: zod.number(),
      answerCount: zod.number(),
      viewCount: zod.number(),
      authorId: zod.number(),
      authorUsername: zod.string(),
      authorDisplayName: zod.string(),
      authorAvatarUrl: zod.string().nullish(),
      createdAt: zod.coerce.date(),
      updatedAt: zod.coerce.date(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  totalPages: zod.number(),
});

/**
 * @summary Create a new question
 */
export const CreateQuestionBody = zod.object({
  title: zod.string(),
  body: zod.string(),
  category: zod.string(),
  tags: zod.array(zod.string()).optional(),
});

/**
 * @summary Get question with answers
 */
export const GetQuestionParams = zod.object({
  id: zod.coerce.number(),
});

export const GetQuestionResponse = zod.object({
  question: zod.object({
    id: zod.number(),
    title: zod.string(),
    body: zod.string(),
    category: zod.string(),
    tags: zod.array(zod.string()),
    status: zod.enum(["open", "answered", "ai_answered"]),
    voteCount: zod.number(),
    answerCount: zod.number(),
    viewCount: zod.number(),
    authorId: zod.number(),
    authorUsername: zod.string(),
    authorDisplayName: zod.string(),
    authorAvatarUrl: zod.string().nullish(),
    createdAt: zod.coerce.date(),
    updatedAt: zod.coerce.date(),
  }),
  answers: zod.array(
    zod.object({
      id: zod.number(),
      body: zod.string(),
      questionId: zod.number(),
      authorId: zod.number().nullish(),
      authorUsername: zod.string(),
      authorDisplayName: zod.string(),
      authorAvatarUrl: zod.string().nullish(),
      isAiGenerated: zod.boolean(),
      isVerified: zod.boolean(),
      verificationNote: zod.string().nullish(),
      isAccepted: zod.boolean(),
      voteCount: zod.number(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Upvote or downvote a question
 */
export const VoteQuestionParams = zod.object({
  id: zod.coerce.number(),
});

export const VoteQuestionBody = zod.object({
  direction: zod.enum(["up", "down"]),
  userId: zod.number().optional(),
});

export const VoteQuestionResponse = zod.object({
  voteCount: zod.number(),
});

/**
 * @summary Toggle a like on a question
 */
export const LikeQuestionParams = zod.object({
  id: zod.coerce.number(),
});

export const LikeQuestionResponse = zod.object({
  liked: zod.boolean(),
  likeCount: zod.number(),
});

/**
 * @summary Submit an answer (goes through AI verification)
 */
export const CreateAnswerParams = zod.object({
  questionId: zod.coerce.number(),
});

export const CreateAnswerBody = zod.object({
  body: zod.string(),
});

/**
 * @summary Upvote or downvote an answer
 */
export const VoteAnswerParams = zod.object({
  id: zod.coerce.number(),
});

export const VoteAnswerBody = zod.object({
  direction: zod.enum(["up", "down"]),
  userId: zod.number().optional(),
});

export const VoteAnswerResponse = zod.object({
  voteCount: zod.number(),
});

/**
 * @summary Toggle a like on an answer
 */
export const LikeAnswerParams = zod.object({
  id: zod.coerce.number(),
});

export const LikeAnswerResponse = zod.object({
  liked: zod.boolean(),
  likeCount: zod.number(),
});

/**
 * @summary Accept an answer as the solution
 */
export const AcceptAnswerParams = zod.object({
  id: zod.coerce.number(),
});

export const AcceptAnswerResponse = zod.object({
  id: zod.number(),
  body: zod.string(),
  questionId: zod.number(),
  authorId: zod.number().nullish(),
  authorUsername: zod.string(),
  authorDisplayName: zod.string(),
  authorAvatarUrl: zod.string().nullish(),
  isAiGenerated: zod.boolean(),
  isVerified: zod.boolean(),
  verificationNote: zod.string().nullish(),
  isAccepted: zod.boolean(),
  voteCount: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Get community dashboard statistics
 */
export const GetDashboardStatsResponse = zod.object({
  totalQuestions: zod.number(),
  totalAnswers: zod.number(),
  totalUsers: zod.number(),
  unansweredCount: zod.number(),
  aiAnsweredCount: zod.number(),
  avgResponseTimeHours: zod.number(),
});

/**
 * @summary Get trending questions
 */
export const GetTrendingQuestionsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  body: zod.string(),
  category: zod.string(),
  tags: zod.array(zod.string()),
  status: zod.enum(["open", "answered", "ai_answered"]),
  voteCount: zod.number(),
  answerCount: zod.number(),
  viewCount: zod.number(),
  authorId: zod.number(),
  authorUsername: zod.string(),
  authorDisplayName: zod.string(),
  authorAvatarUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const GetTrendingQuestionsResponse = zod.array(
  GetTrendingQuestionsResponseItem,
);

/**
 * @summary Get question counts by category
 */
export const GetCategoryStatsResponseItem = zod.object({
  category: zod.string(),
  count: zod.number(),
});
export const GetCategoryStatsResponse = zod.array(GetCategoryStatsResponseItem);

/**
 * @summary Get recent community activity feed
 */
export const GetRecentActivityResponseItem = zod.object({
  id: zod.number(),
  type: zod.enum(["question", "answer", "ai_answer"]),
  title: zod.string(),
  username: zod.string(),
  createdAt: zod.coerce.date(),
});
export const GetRecentActivityResponse = zod.array(
  GetRecentActivityResponseItem,
);

/**
 * @summary Trigger AI to answer unanswered questions older than 24hrs
 */
export const TriggerAiAnswerCheckResponse = zod.object({
  processed: zod.number(),
  answered: zod.number(),
});
