/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface CreateUserBody {
  username: string;
  displayName: string;
  avatarUrl?: string;
}

export interface User {
  id: number;
  /** @nullable */
  clerkUserId?: string | null;
  username: string;
  /** @nullable */
  email?: string | null;
  displayName: string;
  /** @nullable */
  avatarUrl?: string | null;
  reputation: number;
  questionsCount: number;
  answersCount: number;
  createdAt: string;
}

export interface UpsertCurrentUserBody {
  username: string;
  displayName: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
}

export interface CreateQuestionBody {
  title: string;
  body: string;
  category: string;
  tags?: string[];
}

export type QuestionStatus =
  (typeof QuestionStatus)[keyof typeof QuestionStatus];

export const QuestionStatus = {
  open: "open",
  answered: "answered",
  ai_answered: "ai_answered",
} as const;

export interface Question {
  id: number;
  title: string;
  body: string;
  category: string;
  tags: string[];
  status: QuestionStatus;
  voteCount: number;
  answerCount: number;
  viewCount: number;
  authorId: number;
  authorUsername: string;
  authorDisplayName: string;
  /** @nullable */
  authorAvatarUrl?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Answer {
  id: number;
  body: string;
  questionId: number;
  /** @nullable */
  authorId?: number | null;
  authorUsername: string;
  authorDisplayName: string;
  /** @nullable */
  authorAvatarUrl?: string | null;
  isAiGenerated: boolean;
  isVerified: boolean;
  /** @nullable */
  verificationNote?: string | null;
  isAccepted: boolean;
  voteCount: number;
  createdAt: string;
}

export interface QuestionDetail {
  question: Question;
  answers: Answer[];
}

export interface PaginatedQuestions {
  questions: Question[];
  total: number;
  page: number;
  totalPages: number;
}

export interface CreateAnswerBody {
  body: string;
}

export type VoteBodyDirection =
  (typeof VoteBodyDirection)[keyof typeof VoteBodyDirection];

export const VoteBodyDirection = {
  up: "up",
  down: "down",
} as const;

export interface VoteBody {
  direction: VoteBodyDirection;
  userId?: number;
}

export interface LikeResult {
  liked: boolean;
  likeCount: number;
}

export interface VoteResult {
  voteCount: number;
}

export interface DashboardStats {
  totalQuestions: number;
  totalAnswers: number;
  totalUsers: number;
  unansweredCount: number;
  aiAnsweredCount: number;
  avgResponseTimeHours: number;
}

export interface CategoryStat {
  category: string;
  count: number;
}

export type ActivityItemType =
  (typeof ActivityItemType)[keyof typeof ActivityItemType];

export const ActivityItemType = {
  question: "question",
  answer: "answer",
  ai_answer: "ai_answer",
} as const;

export interface ActivityItem {
  id: number;
  type: ActivityItemType;
  title: string;
  username: string;
  createdAt: string;
}

export interface AiCheckResult {
  processed: number;
  answered: number;
}

export type ListQuestionsParams = {
  category?: string;
  status?: ListQuestionsStatus;
  sort?: ListQuestionsSort;
  search?: string;
  page?: number;
  limit?: number;
};

export type ListQuestionsStatus =
  (typeof ListQuestionsStatus)[keyof typeof ListQuestionsStatus];

export const ListQuestionsStatus = {
  open: "open",
  answered: "answered",
  ai_answered: "ai_answered",
} as const;

export type ListQuestionsSort =
  (typeof ListQuestionsSort)[keyof typeof ListQuestionsSort];

export const ListQuestionsSort = {
  recent: "recent",
  popular: "popular",
  unanswered: "unanswered",
} as const;
