/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateUserBody {
  username: string;
  displayName: string;
  avatarUrl?: string;
}
