/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */
import type { ListQuestionsSort } from "./listQuestionsSort";
import type { ListQuestionsStatus } from "./listQuestionsStatus";

export type ListQuestionsParams = {
  category?: string;
  status?: ListQuestionsStatus;
  sort?: ListQuestionsSort;
  search?: string;
  page?: number;
  limit?: number;
};
