/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */

export type ListQuestionsStatus =
  (typeof ListQuestionsStatus)[keyof typeof ListQuestionsStatus];

export const ListQuestionsStatus = {
  open: "open",
  answered: "answered",
  ai_answered: "ai_answered",
} as const;
