/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionStatus } from "./questionStatus";

export interface Question {
  id: number;
  title: string;
  body: string;
  category: string;
  tags: string[];
  status: QuestionStatus;
  voteCount: number;
  answerCount: number;
  viewCount: number;
  authorId: number;
  authorUsername: string;
  authorDisplayName: string;
  /** @nullable */
  authorAvatarUrl?: string | null;
  createdAt: Date;
  updatedAt: Date;
}
