/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */

export interface User {
  id: number;
  /** @nullable */
  clerkUserId?: string | null;
  username: string;
  /** @nullable */
  email?: string | null;
  displayName: string;
  /** @nullable */
  avatarUrl?: string | null;
  reputation: number;
  questionsCount: number;
  answersCount: number;
  createdAt: Date;
}
