/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */

export type VoteBodyDirection =
  (typeof VoteBodyDirection)[keyof typeof VoteBodyDirection];

export const VoteBodyDirection = {
  up: "up",
  down: "down",
} as const;
