/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Opal Zeta Community Q&A API
 * OpenAPI spec version: 0.1.0
 */
import type { VoteBodyDirection } from "./voteBodyDirection";

export interface VoteBody {
  direction: VoteBodyDirection;
  userId?: number;
}
